### PR TITLE
adding extra laser sounds and associated config

### PR DESCRIPTION
**Pull request by phkb**

### CODE REVIEW

**Comment by AnotherCommander** [comment]
Looking good. I think we need to add the names of the new sounds' creators and the license under which those sounds are published in our Readme.pdf for proper crediting and attribution, right? @phkb can you please add this? We can then merge.

**Comment by phkb** [comment]
Will do. Stand by.

**Comment by AnotherCommander** [comment]
The binary resources submodule does not have a revision numbered 609420. We need to be careful here. I think it would be best if I apply the commit directly on master so that we avoid complications related to commits with submodules.

**Comment by phkb** [comment]
I'm happy with that. I thought I did the submodule stuff right.. oh well.

**Comment by AnotherCommander** [comment]
It is likely that you have not done anything wrong, I am just not sure how this merge would be supposed to work. The way i understand it, the PR is asking for the binary resources submodule index on master to be pointed to revision 609420. I expect that if you do a git rev-parse HEAD inside oolite-binary-resources, you should see that number popping up. If it does, you could try a push from inside oolite-binary-resources so that the latest revision on github gets updated to reflect that revision. If that happens, then we can simply do the merge and all will be OK. At least, that's what I think.

Or I can try to do all this myself and have the full responsibility in case of a mess up.

**Comment by AnotherCommander** [comment]
I'll give it a try myself. Once all files are in and well, we can close this PR with a note that it has been manually merged with master. Fingers crossed.

**Comment by phkb** [comment]
I've got 609420 after that command

**Comment by phkb** [comment]
So happy to do the push if you like

**Comment by AnotherCommander** [comment]
OK, just saw your last message. Do you want to do a git push from the submodule folder?

**Comment by phkb** [comment]
sure. Stand by.

**Comment by phkb** [comment]
Hmm. Says I'm not currently on a branch

**Comment by phkb** [comment]
says I need to do a "git push origin HEAD:name-of-remote-branch"
Stand by.

**Comment by AnotherCommander** [comment]
OK. Do a git checkout master. Then do a git status and let me know what it gives you.

**Comment by phkb** [comment]
$ git checkout master
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  609420c adding new custom laser sound files

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 609420c

Switched to branch 'master'
Your branch is up to date with 'origin/master'.

**Comment by AnotherCommander** [comment]
Can you try doing now git checkout 609420c and then git status again?

**Comment by phkb** [comment]
$ git checkout 609420c
Note: checking out '609420c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 609420c adding new custom laser sound files

$ git status
HEAD detached at 609420c
nothing to commit, working tree clean

**Comment by AnotherCommander** [comment]
Oh man, I am getting scared. My github-foo is too poor to handle this. Let me do the commits manually. I think it will be safer that way.

**Comment by phkb** [comment]
Yep, mine too!

**Comment by AnotherCommander** [comment]
Hopefully I did this manually without having the universe implode on me. Please check that all is OK so we can close this PR.

**Comment by phkb** [comment]
All looks good from my end. Sounds, config, PDF all in place.

**Comment by AnotherCommander** [comment]
Many thanks. This PR will now be closed, after having been merged manually into master.

**Pull request closed without merging**
