### PR TITLE
Fix compilation on Gentoo

### PR DESCRIPTION
**Pull request by kanthoney**
Fix for issue 139, the compilation failure on Gentoo.  Also tested on Debian.

### CODE REVIEW

**Comment by KonstantinosSykas** [comment]
I need some time to check making of Linux distro-neutral installer.

**Comment by kanthoney** [comment]
No problem.  I don't see any point in putting this in pre-1.82 release anyway, as it's only going to affect people building from source.

**Comment by KonstantinosSykas** [comment]
Making of Linux distro-neutral installer checked OK for both 32bit and 64bit architectures. 
May the Learned Elders of Oolite decide the future of this pull request.

**Comment by cim--** [comment]
I think it should probably be merged - as I said on #139, a better post-1.82 fix would be to take the OF macro out of the Minizip code entirely. If it seems to work on all the various platforms we have it should be safe.

**Pull request merged**
