### PR TITLE
Fast enumeration migration

### PR DESCRIPTION
**Pull request by MaddTheSane**
These patches migrate the usage of many `NSEnumeration` to this project's `foreach` and `foreachkey`, which translates to `for(...in...)` on systems that support it.

### CODE REVIEW

**Comment by kanthoney** [comment]
Here's what the first screen after game start looks like under Linux:

snapshot3

**Comment by MaddTheSane** [comment]
You got farther than I did when I tried to launch it (although I do have my own patches…). I'm also discovering places where the code expects values in an `NSDictionary` and not the keys.

I'll be fixing some of them soon.

Later: Okay, now I'm getting to the point with the blank screen.

**Comment by MaddTheSane** [comment]
oops, one moment.

**Comment by MaddTheSane** [comment]
I accidentally pushed a commit that changed the submodules. This should be fixed now.

**Comment by kanthoney** [comment]
So you're issuing a pull request without actually getting it to work first?

**Comment by MaddTheSane** [comment]
I assumed that the edits wouldn't break the game. I was wrong.

**Pull request closed without merging**
