### PR TITLE
Adds functions to access and change key values in screenbackgrounds.plist via JS 

### PR DESCRIPTION
**Pull request by phkb**
Currently the function names are "getScreenBackgroundDefault(keyname)" and "setScreenBackgroundDefault(keyname, guiTextureSpecifier)". 
This change will provide a way for scripts to see and override whatever settings have been loaded from screenbackgrounds.plist. Any changes are during the current play session only and are not saved.

### CODE REVIEW

**Comment by phkb** [comment]
Um, I think I just revealed my n00biness with Git - I think this is saying all my commits from the "display_color" branch are included in this one. If I have messed it up please close and/or delete it and I'll try again!

**Comment by phkb** [comment]
I changed the functions names to something a bit more consistent: "setScreenBackgroundForKey" and "getScreenBackgroundForKey".

**Comment by AnotherCommander** [comment]
The diff on this PR still shows display_color stuff for equipment. Can you try rebasing it on the current master or close this PR and re-open it with the correct base revision?

**Comment by phkb** [comment]
I thought I'd muffed it! Thanks a_c.

**Pull request closed without merging**
